openapi: 3.2.0
info:
  title: loopay-api Document Type API
  version: 3.2.0
  description: '## Loopay open API

    You will find a complete guide and information to start working with Loopay integrations as soon as possible, as well as support if you get lost, so let''s dive right in!'
  contact:
    name: Loopay Team
servers:
- url: https://api.loopay.com
tags:
- name: Document type
paths:
  /documentTypes:
    get:
      x-controller-name: DocumentType
      x-operation-name: documentTypeBases
      tags:
      - Document type
      description: '## Get documents types

        Get all document types'
      responses:
        '200':
          description: Array of document types
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    type:
                      type: string
                      example: CC
                    countryId:
                      type: integer
                      example: 1
      parameters:
      - name: authorization
        in: query
        schema:
          type: string
      operationId: DocumentType.documentTypeBases
      summary: Document type document type bases
      x-summary-source: derived
